// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package policy

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*txOptionsMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (t TxOptions) MarshalJSON() ([]byte, error) {
	type TxOptions struct {
		KnownAccounts  KnownAccounts   `json:"knownAccounts"`
		BlockNumberMin *hexutil.Big    `json:"blockNumberMin,omitempty"`
		BlockNumberMax *hexutil.Big    `json:"blockNumberMax,omitempty"`
		TimestampMin   *hexutil.Uint64 `json:"timestampMin,omitempty"`
		TimestampMax   *hexutil.Uint64 `json:"timestampMax,omitempty"`
	}
	var enc TxOptions
	enc.KnownAccounts = t.KnownAccounts
	enc.BlockNumberMin = (*hexutil.Big)(t.BlockNumberMin)
	enc.BlockNumberMax = (*hexutil.Big)(t.BlockNumberMax)
	enc.TimestampMin = (*hexutil.Uint64)(t.TimestampMin)
	enc.TimestampMax = (*hexutil.Uint64)(t.TimestampMax)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (t *TxOptions) UnmarshalJSON(input []byte) error {
	type TxOptions struct {
		KnownAccounts  *KnownAccounts  `json:"knownAccounts"`
		BlockNumberMin *hexutil.Big    `json:"blockNumberMin,omitempty"`
		BlockNumberMax *hexutil.Big    `json:"blockNumberMax,omitempty"`
		TimestampMin   *hexutil.Uint64 `json:"timestampMin,omitempty"`
		TimestampMax   *hexutil.Uint64 `json:"timestampMax,omitempty"`
	}
	var dec TxOptions
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.KnownAccounts != nil {
		t.KnownAccounts = *dec.KnownAccounts
	}
	if dec.BlockNumberMin != nil {
		t.BlockNumberMin = (*big.Int)(dec.BlockNumberMin)
	}
	if dec.BlockNumberMax != nil {
		t.BlockNumberMax = (*big.Int)(dec.BlockNumberMax)
	}
	if dec.TimestampMin != nil {
		t.TimestampMin = (*uint64)(dec.TimestampMin)
	}
	if dec.TimestampMax != nil {
		t.TimestampMax = (*uint64)(dec.TimestampMax)
	}
	return nil
}